export const BBOX_COLORS = {
  text: '#33B1FF',
  title: '#1890FF',
  header: '#A6A6A6',
  footer: '#A6A6A6',
  table: '#52C41A',
  table_caption: '#95DE64',
  figure: '#FA8C16',
  figure_caption: '#FFC069',
  figure_title: '#FFC069',
  equation: '#722ED1',
  display_formula: '#722ED1',
  doc_title: '#13C2C2',
  paragraph_title: '#13C2C2',
  abstract: '#2F54EB',
  footnote: '#D9D9D9',
  aside_text: '#595959',
  reference: '#8C8C8C',
  formula: '#722ED1',
  image: '#FA8C16',
  image_caption: '#FFC069',
  number: '#D9D9D9',
  page_number: '#D9D9D9',
  page_footnote: '#D9D9D9',
  droped_text: '#595959',
  code_txt: '#2F54EB',
  code_txt_caption: '#8C8C8C',
} as const;

export const TYPE_LABELS: Record<string, string> = {
  text: 'Text',
  title: 'Title',
  header: 'Header',
  footer: 'Footer',
  table: 'Table',
  table_caption: 'Table Caption',
  figure: 'Figure',
  figure_caption: 'Figure Caption',
  figure_title: 'Figure Title',
  equation: 'Equation',
  display_formula: 'Display Formula',
  doc_title: 'Doc Title',
  paragraph_title: 'Paragraph Title',
  abstract: 'Abstract',
  footnote: 'Footnote',
  aside_text: 'Aside Text',
  reference: 'Reference',
  formula: 'Formula',
  image: 'Image',
  image_caption: 'Image Caption',
  number: 'Number',
  page_number: 'Page Number',
  page_footnote: 'Page Footnote',
  droped_text: 'Dropped Text',
  code_txt: 'Code',
  code_txt_caption: 'Code Caption',
} as const;

export const TYPE_ICONS: Record<string, string> = {
  text: '📝',
  title: '📝',
  header: '📝',
  footer: '📝',
  table: '📊',
  table_caption: '📊',
  figure: '🖼️',
  figure_caption: '🖼️',
  figure_title: '🖼️',
  equation: '📐',
  display_formula: '📐',
  doc_title: '📖',
  paragraph_title: '📑',
  abstract: '📝',
  footnote: '📑',
  aside_text: '💬',
  reference: '📑',
  formula: '📐',
  image: '🖼️',
  image_caption: '🖼️',
  number: '🔢',
  page_number: '🔢',
  page_footnote: '📑',
  droped_text: '📝',
  code_txt: '💻',
  code_txt_caption: '💻',
} as const;

export const ELEMENT_TYPES = [
  'text',
  'title',
  'header',
  'footer',
  'table',
  'table_caption',
  'figure',
  'figure_title',
  'figure_caption',
  'equation',
  'display_formula',
  'image',
  'image_caption',
  'number',
  'page_number',
  'page_footnote',
] as const;
