export const BBOX_COLORS = {
  text: '#33B1FF',
  title: '#1890FF',
  header: '#A6A6A6',
  footer: '#A6A6A6',
  table: '#52C41A',
  table_caption: '#95DE64',
  figure: '#FA8C16',
  figure_caption: '#FFC069',
  equation: '#722ED1',
  doc_title: '#13C2C2',
  paragraph_title: '#13C2C2',
  abstract: '#2F54EB',
  footnote: '#D9D9D9',
  aside_text: '#595959',
  reference: '#8C8C8C',
  formula: '#722ED1',
} as const;

export const TYPE_LABELS: Record<string, string> = {
  text: 'Text',
  title: 'Title',
  header: 'Header',
  footer: 'Footer',
  table: 'Table',
  table_caption: 'Table Caption',
  figure: 'Figure',
  figure_caption: 'Figure Caption',
  equation: 'Equation',
  doc_title: 'Doc Title',
  paragraph_title: 'Paragraph Title',
  abstract: 'Abstract',
  footnote: 'Footnote',
  aside_text: 'Aside Text',
  reference: 'Reference',
  formula: 'Formula',
} as const;

export const TYPE_ICONS: Record<string, string> = {
  text: '📝',
  title: '📝',
  header: '📝',
  footer: '📝',
  table: '📊',
  table_caption: '📊',
  figure: '🖼️',
  figure_caption: '🖼️',
  equation: '📐',
  doc_title: '📖',
  paragraph_title: '📑',
  abstract: '📝',
  footnote: '📑',
  aside_text: '💬',
  reference: '📑',
  formula: '📐',
} as const;

export const ELEMENT_TYPES = [
  'text',
  'title',
  'header',
  'footer',
  'table',
  'table_caption',
  'figure',
  'figure_caption',
  'equation',
] as const;
